apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeserver
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata: 
      labels:
        app: server
    spec: 
      containers:
        - name: nodeserver
          image: srsantosdev/k8s-node-test
          ports:
            - containerPort: 3333